# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.17/metricbeat-module-nginx.html

- module: nginx
  metricsets:
     - stubstatus
  period: 10s

  # Nginx hosts
  hosts: ["http://localhost:8080/status"]

  # Path to server status. Default nginx_status
  #server_status_path: "nginx_status"

  #username: "user"
  #password: "secret"
